import csv
import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

import pytest

from glucotrace.commands import encode_main
from glucotrace.data import MG_DL_PER_MMOL_L, load_cgm_csv
from test_inference import make_checkpoint

TITLE = ["Glucose Data", "Generated on", "03-02-2024 10:15 AM UTC", "Generated by", "Test Person"]
HEADER = [
    "Device", "Serial Number", "Device Timestamp", "Record Type",
    "Historic Glucose {unit}", "Scan Glucose {unit}",
    "Non-numeric Rapid-Acting Insulin", "Rapid-Acting Insulin (units)",
    "Non-numeric Food", "Carbohydrates (grams)", "Notes",
]


def us_stamp(moment: datetime) -> str:
    return moment.strftime("%m-%d-%Y %I:%M %p")


def eu_stamp(moment: datetime) -> str:
    return moment.strftime("%d-%m-%Y %H:%M")


def write_libreview(
    path: Path,
    values: list[str],
    *,
    start: datetime = datetime(2024, 3, 1, 11, 30),
    unit: str = "mg/dL",
    stamp=us_stamp,
) -> Path:
    """A synthetic LibreView-style export with scans, food, and notes mixed in."""

    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(TITLE)
        writer.writerow([column.format(unit=unit) for column in HEADER])
        blank = [""] * len(HEADER)
        for index, value in enumerate(values):
            moment = start + timedelta(minutes=15 * index)
            row = list(blank)
            row[0], row[1], row[2], row[3], row[4] = "FreeStyle Libre 2", "SYN0001", stamp(moment), "0", value
            writer.writerow(row)
            if index == 1:  # a scan, a food entry, and a note between readings
                for record_type, column, cell in (("1", 5, "999"), ("5", 9, "30"), ("6", 10, "note")):
                    extra = list(blank)
                    extra[0], extra[2], extra[3], extra[column] = "FreeStyle Libre 2", stamp(moment + timedelta(minutes=4)), record_type, cell
                    writer.writerow(extra)
    return path


def test_us_export_reads_only_historic_readings_at_15_minutes(tmp_path: Path) -> None:
    path = write_libreview(tmp_path / "us.csv", ["101", "104", "110", "115"])
    series = load_cgm_csv(path, input_format="libreview")
    observed = series.observed_mask.nonzero().flatten().tolist()
    assert observed == [0, 3, 6, 9]  # every 15 minutes on the 5-minute grid
    assert series.glucose[observed].tolist() == [101, 104, 110, 115]
    # 11:30 AM, 11:45 AM, 12:00 PM, 12:15 PM: the noon crossing is read correctly
    assert [series.timestamps[i].strftime("%H:%M") for i in observed] == ["11:30", "11:45", "12:00", "12:15"]
    assert series.input_unit == "mg/dL"


def test_midnight_am_is_hour_zero(tmp_path: Path) -> None:
    path = write_libreview(tmp_path / "night.csv", ["100", "100"], start=datetime(2024, 3, 1, 23, 45))
    series = load_cgm_csv(path, input_format="libreview")
    assert series.timestamps[3] == datetime(2024, 3, 2, 0, 0)


def test_european_mmol_export_with_decimal_commas(tmp_path: Path) -> None:
    path = write_libreview(
        tmp_path / "eu.csv", ["5,6", "6,1", "7,0"],
        start=datetime(2024, 3, 21, 8, 0), unit="mmol/L", stamp=eu_stamp,
    )
    series = load_cgm_csv(path, input_format="libreview")
    assert series.timestamps[0] == datetime(2024, 3, 21, 8, 0)  # day 21, month 3
    assert series.glucose[0].item() == pytest.approx(5.6 * MG_DL_PER_MMOL_L)
    assert series.input_unit == "mmol/L"
    with pytest.raises(ValueError, match="declares mmol/L"):
        load_cgm_csv(path, input_format="libreview", unit="mg/dL")


def test_ambiguous_dates_are_refused_not_guessed(tmp_path: Path) -> None:
    path = write_libreview(
        tmp_path / "ambiguous.csv", ["100", "105"],
        start=datetime(2024, 3, 5, 9, 0), stamp=eu_stamp,  # 05-03-2024: May 3 or March 5?
    )
    with pytest.raises(ValueError, match="--date-order"):
        load_cgm_csv(path, input_format="libreview")
    as_dmy = load_cgm_csv(path, input_format="libreview", date_order="dmy")
    as_mdy = load_cgm_csv(path, input_format="libreview", date_order="mdy")
    assert as_dmy.timestamps[0] == datetime(2024, 3, 5, 9, 0)
    assert as_mdy.timestamps[0] == datetime(2024, 5, 3, 9, 0)


def test_lo_and_hi_follow_the_out_of_range_policy(tmp_path: Path) -> None:
    path = write_libreview(tmp_path / "range.csv", ["LO", "120", "HI"])
    missing = load_cgm_csv(path, input_format="libreview")
    assert missing.out_of_range_count == 2
    assert missing.observed_mask.nonzero().flatten().tolist() == [3]
    clamped = load_cgm_csv(path, input_format="libreview", out_of_range="clamp")
    assert clamped.glucose[[0, 3, 6]].tolist() == [40, 120, 500]  # Libre limits


def test_other_files_are_not_mistaken_for_libreview(tmp_path: Path) -> None:
    path = tmp_path / "plain.csv"
    path.write_text("timestamp,glucose\n2024-03-01T08:00:00,100\n", encoding="utf-8")
    with pytest.raises(ValueError, match="not a LibreView export"):
        load_cgm_csv(path, input_format="libreview")


def test_encode_command_accepts_libreview(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    checkpoint = make_checkpoint(tmp_path / "model.pt")  # 12-position (1-hour) test model
    path = write_libreview(tmp_path / "day.csv", ["101", "104", "110", "115", "112"])
    argv = sys.argv
    sys.argv = ["glucotrace encode", str(path), "--format", "libreview", "--checkpoint", str(checkpoint)]
    try:
        encode_main()
    finally:
        sys.argv = argv
    payload = json.loads(capsys.readouterr().out)
    assert payload["input"]["input_format"] == "libreview"
    assert len(payload["fingerprint"]) == 16
